# Generated by Django 3.1.14 on 2022-03-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_expense_repeat_next_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='import_reference',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
