# Generated by Django 3.1.14 on 2022-03-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_in_n_out'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddField(
            model_name='expense',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
